# Source: https://hub.docker.com/r/atcommons/mlflow-server
version: '3'

services:
  mlflow:
    build:
      context: mlflow/
      args:
        MLFLOW_VERSION: ${MLFLOW_VERSION}
    ports:
      - "5000:5000"
    environment:
      MLFLOW_TRACKING_URI: sqlite:////mlflow/mlflow.db
      ARTIFACTS_RELATIVE_PATH: ./artifacts
    volumes:
      - ./run_env/data:/mlflow
